version: '3'

services:
  db:
    image: mariadb:10.8
    container_name: db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - gb-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1-fpm-alpine
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - gb-network
volumes:
  dbdata:

networks:
  gb-network:
    driver: bridge
