version: '3.1'

services:
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=12345
    ports:
      - 80:80
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge

